apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: demo-votingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-pod
      app: demo-votingapp
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-votingapp
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-votingapp
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector: 
      name: redis-pod
      app: demo-votingapp
  
