apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultapp-deploy
  labels:
    name: resultapp-deploy
    app: demo-votingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: resultapp-pod
      app: demo-votingapp
  template:
    metadata:
      name: resultapp-pod
      labels:
        name: resultapp-pod
        app: demo-votingapp
    spec:
      containers:
        - name: resultapp
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-votingapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector: 
      name: resultapp-pod
      app: demo-votingapp
