apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-deploy
  labels:
    name: votingapp-deploy
    app: demo-votingapp
spec:
  replicas: 2
  selector:
    matchLabels:
       name: votingapp-pod
       app: demo-votingapp
  template:
    metadata:
      name: votingapp-pod
      labels:
        name: votingapp-pod
        app: demo-votingapp
    spec:
      containers:
      - name: votingapp
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-votingapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector: 
      name: votingapp-pod
      app: demo-votingapp
  
